# In _config.yml
title: Johnsons Website
description: Exploring technology, crafting, and learning one project at a time
theme: jekyll-theme-architect

# Add navigation links
nav:
  - name: "Home"
    link: /
  - name: "About"
    link: /about
  - name: "Science Hour"
    link: /sciencehour

# Add new collection for Science Hour events
collections:
  sciencehour:
    output: true
    permalink: /sciencehour/:title/
